require("prototypes.item")
require("prototypes.recipe")
require("prototypes.entity.asteroid")
require("prototypes.entity.steam-furnace")
require("prototypes.entity.simple-heat-exchanger")
require("prototypes.entity.sublimator")