require("prototypes.item")
require("prototypes.entity.asteroid")
require("prototypes.entity.solar-inserter")
require("prototypes.entity.steam-buildings")
require("prototypes.entity.simple-heat-exchanger")
require("prototypes.entity.sublimator")
require("prototypes.entity.solar-heater")
require("prototypes.entity.simple-heat-pipe")
require("prototypes.entity.iron-electric-pole")
require("prototypes.environment.space-rock")
require("prototypes.entity.station")

require("prototypes.recipe")
